package com.brandsin.driver.ui.main.home

data class Order(
    val address_id: Int,
    val amount: String,
    val billing: Billing,
    val comments: List<Any>?=null,
    val created_at: String,
    val created_by: Int,
    val currency: String,
    val deleted_at: Any,
    val delivery_time: String,
    val delivery_time_store: Any,
    val device_type: String,
    val discount_id: Int,
    val discount_value: String,
    val driver_id: Any,
    val gifter_mobile: Any,
    val gifter_name: Any,
    val has_packaging: Int,
    val id: Int?,
    val is_rated: Boolean,
    val order_number: String,
    val order_type: String,
    val orders_key: String,
    val packaging_price: String,
    val preparing_time_store: Any,
    val shipping: Shipping,
    val status: String,
    val statuses_log: List<StatusesLog>,
    val store_id: Int,
    val transaction_no: String,
    val updated_at: String,
    val updated_by: Int,
    val user: User,
    val user_id: Int,
    val user_notes: Any
)